version: '3'

services:
  db:
    image: postgres:13.6-alpine
    container_name: postgresql_tasklist_app
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
      # 文字コードにUTF-8を設定。ロケールはソート性能対策としてCを設定。
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
